// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXehA16vuDOyzCWNQJgU5rqV8byXTrTc',
    appId: '1:791318946064:web:afa01a9ac1abb67be48595',
    messagingSenderId: '791318946064',
    projectId: 'drug-discovery-app',
    authDomain: 'drug-discovery-app.firebaseapp.com',
    storageBucket: 'drug-discovery-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpIVigbj4D0T88AytyFkgH3-saun81BoY',
    appId: '1:791318946064:android:38d87ad2ccb9090ce48595',
    messagingSenderId: '791318946064',
    projectId: 'drug-discovery-app',
    storageBucket: 'drug-discovery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRChoZjMMEsDhmS7crs3sEfkyZZnKcgz8',
    appId: '1:791318946064:ios:8f460965571aaf03e48595',
    messagingSenderId: '791318946064',
    projectId: 'drug-discovery-app',
    storageBucket: 'drug-discovery-app.firebasestorage.app',
    iosBundleId: 'com.example.drugDiscovery',
  );
}
